language: objective-c
notifications:
  email: false
install:
  - bundle install
  - bundle exec pod install
script:
  - xctool clean build -workspace Conway.xcworkspace -scheme Conway
  - xctool test -workspace Conway.xcworkspace -scheme Conway -sdk iphonesimulator
